import React, { useEffect } from 'react';
import AutocompleteInput from '../ui/AutocompleteInput';
interface Props { attrs:Record<string,string>; onChange:(k:string,v:string)=>void; onReady:(c:boolean)=>void; }
const F=({label,req,ch}:{label:string;req?:boolean;ch:React.ReactNode})=>(<div><label className="text-[10px] font-bold text-muted-foreground uppercase tracking-wide block mb-1.5">{label}{req&&<span className="text-dz-red ml-0.5">*</span>}</label>{ch}</div>);
const Sel=({value,onChange,opts,ph}:any)=>(<select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full bg-muted border border-border rounded-xl px-3 py-3 text-sm outline-none focus:border-dz-green cursor-pointer"><option value="">{ph}</option>{opts.map((o:any)=><option key={o.value||o} value={o.value||o}>{o.label||o}</option>)}</select>);
const SECTORS=['Informatique & Télécoms','BTP & Génie Civil','Santé & Médical','Éducation & Formation','Commerce & Vente','Finance & Comptabilité','Industrie & Production','Transport & Logistique','Hôtellerie & Tourisme','Agriculture','Droit & Juridique','Marketing & Communication','Ressources Humaines','Administration & Secrétariat','Architecture & Design','Énergie & Environnement','Pétrole & Gaz','Agroalimentaire','Artisanat','Autre'];
const COMPANIES=['Administration publique','Ministère','Entreprise privée (PME)','Grande entreprise','Multinationale','Startup','ONG / Association','Professionnel libéral','Auto-entrepreneur','Particulier'];
export default function EmploiForm({attrs,onChange,onReady}:Props){
  useEffect(()=>{ onReady(['contract_type','sector'].every(k=>!!attrs[k])); },[attrs]);
  return(<div className="space-y-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
    <F label="Type de contrat" req ch={<Sel value={attrs.contract_type} onChange={(v:string)=>onChange('contract_type',v)} opts={[{value:'cdi',label:'CDI — Contrat durée indéterminée'},{value:'cdd',label:'CDD — Contrat durée déterminée'},{value:'cdd6m',label:'CDD 6 mois'},{value:'cdd3m',label:'CDD 3 mois'},{value:'parttime',label:'Temps partiel'},{value:'freelance',label:'Freelance / Mission ponctuelle'},{value:'internship',label:'Stage (rémunéré)'},{value:'apprentice',label:'Alternance / Apprentissage'},{value:'seasonal',label:'Saisonnier'},{value:'wanted',label:'Demande d\'emploi (cherche poste)'}]} ph="Type de contrat"/>}/>
    <F label="Secteur d'activité" req ch={<Sel value={attrs.sector} onChange={(v:string)=>onChange('sector',v)} opts={SECTORS} ph="Secteur"/>}/>
    <F label="Intitulé du poste" req ch={<AutocompleteInput value={attrs.job_title||''} onChange={v=>onChange('job_title',v)} suggestions={['Développeur Full Stack','Ingénieur Génie Civil','Médecin Généraliste','Comptable','Commercial Terrain','Chef de Projet','Architecte','Infirmier(ère)','Enseignant(e)','Chef Cuisinier','Chauffeur PL','Technicien Maintenance','Responsable RH','Directeur Commercial','Designer Graphique','Community Manager','Data Analyst','DevOps Engineer','Pharmacien(ne)','Juriste d\'entreprise']} placeholder="Ex: Développeur React Senior"/>}/>
    <F label="Niveau d'expérience" ch={<Sel value={attrs.experience} onChange={(v:string)=>onChange('experience',v)} opts={[{value:'0',label:'Débutant accepté (0 an)'},{value:'1_2',label:'1 à 2 ans d\'expérience'},{value:'2_5',label:'2 à 5 ans'},{value:'5_10',label:'5 à 10 ans'},{value:'10plus',label:'10 ans et plus'}]} ph="Expérience requise"/>}/>
    <F label="Salaire (DA/mois)" ch={<div className="flex gap-2"><input type="number" step="5000" value={attrs.salary_min||''} onChange={e=>onChange('salary_min',e.target.value)} placeholder="Min" className="flex-1 bg-muted border border-border rounded-xl px-3 py-3 text-sm outline-none focus:border-dz-green"/><span className="self-center text-muted-foreground">—</span><input type="number" step="5000" value={attrs.salary_max||''} onChange={e=>onChange('salary_max',e.target.value)} placeholder="Max" className="flex-1 bg-muted border border-border rounded-xl px-3 py-3 text-sm outline-none focus:border-dz-green"/></div>}/>
    <F label="Mode de travail" ch={<Sel value={attrs.work_mode} onChange={(v:string)=>onChange('work_mode',v)} opts={[{value:'onsite',label:'Présentiel (sur site)'},{value:'remote',label:'Télétravail intégral'},{value:'hybrid',label:'Hybride (mix présentiel/télétravail)'},{value:'travel',label:'Déplacement requis'}]} ph="Mode de travail"/>}/>
    <F label="Type d'employeur" ch={<Sel value={attrs.company_type} onChange={(v:string)=>onChange('company_type',v)} opts={COMPANIES} ph="Type d'entreprise"/>}/>
    <F label="Niveau d'études requis" ch={<Sel value={attrs.education} onChange={(v:string)=>onChange('education',v)} opts={[{value:'any',label:'Tous niveaux'},{value:'bac',label:'BAC'},{value:'bac2',label:'BAC+2 (DUT/BTS)'},{value:'bac3',label:'BAC+3 (Licence)'},{value:'bac5',label:'BAC+5 (Master/Ingénieur)'},{value:'bac8',label:'Doctorat / PhD'}]} ph="Niveau d'études"/>}/>
  </div>
  <F label="Avantages proposés" ch={<div className="flex flex-wrap gap-2">{['Véhicule de service','Téléphone de service','Mutuelle / Assurance','Tickets restaurant','Logement de fonction','Formation continue','Prime annuelle','13ème mois','Transport pris en charge','Heures sup rémunérées'].map(a=>{const vals=(attrs.benefits||'').split(',').filter(Boolean);const on=vals.includes(a);return(<button key={a} type="button" onClick={()=>{const n=on?vals.filter(v=>v!==a):[...vals,a];onChange('benefits',n.join(','));}} className={`px-3 py-1.5 rounded-full text-xs font-semibold border transition-all ${on?'bg-dz-green text-white border-dz-green':'bg-muted border-border text-muted-foreground hover:border-dz-green/40'}`}>{a}</button>);})}</div>}/>
  </div>);
}
