import React, { useEffect } from 'react';
import AutocompleteInput from '../ui/AutocompleteInput';
import { SERVICE_TYPES } from '../../lib/formData';
interface Props { attrs:Record<string,string>; onChange:(k:string,v:string)=>void; onReady:(c:boolean)=>void; }
const F=({label,req,children}:{label:string;req?:boolean;children:React.ReactNode})=>(<div><label className="text-[10px] font-bold text-muted-foreground uppercase tracking-wide block mb-1.5">{label}{req&&<span className="text-dz-red ml-0.5">*</span>}</label>{children}</div>);
const Sel=({value,onChange,opts,ph}:any)=>(<select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full bg-muted border border-border rounded-xl px-3 py-3 text-sm outline-none focus:border-dz-green cursor-pointer"><option value="">{ph}</option>{opts.map((o:any)=><option key={o.value||o} value={o.value||o}>{o.label||o}</option>)}</select>);
export default function ServicesForm({attrs,onChange,onReady}:Props){
  useEffect(()=>{ onReady(['service_type'].every(k=>!!attrs[k])); },[attrs]);
  return(<div className="space-y-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
    <F label="Type de service" req><Sel value={attrs.service_type} onChange={(v:string)=>onChange('service_type',v)} opts={SERVICE_TYPES} ph="Quel service proposez-vous ?"/></F>
    <F label="Disponibilité"><Sel value={attrs.availability} onChange={(v:string)=>onChange('availability',v)} opts={[{value:'immediate',label:'Disponible immédiatement'},{value:'weekdays',label:'Jours ouvrables (Dim-Jeu)'},{value:'weekend',label:'Week-end (Ven-Sam)'},{value:'anytime',label:'7j/7 — 24h/24'},{value:'appointment',label:'Sur rendez-vous uniquement'}]} ph="Disponibilité"/></F>
    <F label="Zone d'intervention"><div className="flex flex-wrap gap-2">{['Ma commune uniquement','Ma wilaya','Wilayas limitrophes','Tout Alger','Tout le Nord','Tout le pays','Déplacement possible'].map(z=>{const on=attrs.zone===z;return(<button key={z} type="button" onClick={()=>onChange('zone',z)} className={`px-3 py-1.5 rounded-full text-xs font-semibold border transition-all ${on?'bg-dz-green text-white border-dz-green':'bg-muted border-border text-muted-foreground hover:border-dz-green/40'}`}>{z}</button>);})}</div></F>
    <F label="Tarification"><Sel value={attrs.pricing_type} onChange={(v:string)=>onChange('pricing_type',v)} opts={[{value:'fixed',label:'Forfait fixe'},{value:'hourly',label:'Tarif horaire'},{value:'daily',label:'Tarif journalier'},{value:'quote',label:'Sur devis (contacter)'},{value:'free',label:'Gratuit / Bénévolat'}]} ph="Type de tarification"/></F>
    <F label="Expérience"><Sel value={attrs.experience} onChange={(v:string)=>onChange('experience',v)} opts={[{value:'0_2',label:'Moins de 2 ans'},{value:'2_5',label:'2 à 5 ans'},{value:'5_10',label:'5 à 10 ans'},{value:'10plus',label:'Plus de 10 ans'}]} ph="Années d'expérience"/></F>
    <F label="Langue(s) parlée(s)"><div className="flex flex-wrap gap-2">{['Arabe','Français','Tamazight','Anglais','Autre'].map(l=>{const vals=(attrs.languages||'').split(',').filter(Boolean);const on=vals.includes(l);return(<button key={l} type="button" onClick={()=>{const n=on?vals.filter(v=>v!==l):[...vals,l];onChange('languages',n.join(','));}} className={`px-3 py-1.5 rounded-full text-xs font-semibold border transition-all ${on?'bg-dz-green text-white border-dz-green':'bg-muted border-border text-muted-foreground hover:border-dz-green/40'}`}>{l}</button>);})}</div></F>
    <F label="Certifications / Agréments"><input type="text" value={attrs.certifications||''} onChange={e=>onChange('certifications',e.target.value)} placeholder="Ex: Agrément SONELGAZ, Certifié PMI, Diplôme d'État…" className="w-full bg-muted border border-border rounded-xl px-4 py-3 text-sm outline-none focus:border-dz-green"/></F>
  </div></div>);
}
